<div>
    <div class="occupy"></div>
    <!-- 脚部 -->
    <footer class="bottombar" >
        <section class="wrap conetnt">
            <div class="l">
                <img class="footer-logo" src="../img/img_footer_logo@2x.png" alt="logo" width="132px" height="38px">
                <p>开课吧，互联网人O2O立体化学习平台，慧科集团深耕教育创新6周年杰作。旨在通过国际领先的智慧职业教育模式，帮助大学生及互联网从业者，享受更为个性、时尚、愉悦的学习体验，获得令人惊艳的学习成就，赢得优质工作机会与职业启程。</p>
                <br>
            </div>
            <div class="r">
                <div>
                    <span>关注我们：</span>
                    <ul class="follow-entry">
                        <li>
                            <a class="icon weibo applypie" href="http://weibo.com/kaikeba" target="_blank">
                                <em class="icon-footer_weibo"></em>
                            </a>
                            <div class="popover">
                                <p>关注开课吧官方微博<br>
                                每日获取最新学习资料</p>
                            </div>
                        </li>
                        <li>
                            <a class="icon wechat applypie">
                                <em class="icon-footer_wechat"></em>
                            </a>
                            <div class="popover">
                                <img src="../img/wechat.png" width="100%" alt="微信公众号二维码">
                                <p>关注开课吧微信公众号<br>
                                每日获取最新学习资料</p>
                            </div>
                        </li>
                        <li>
                            <a class="icon app applypie" href="http://www.kaikeba.com/download" target="_blank">
                                <em class="icon-footer_app"></em>
                            </a>
                            <div class="popover">
                                <img src="../img/app-download.png" width="100%" alt="app下载二维码">
                                <p>下载开课吧APP<br>
                                随时随地在线高效学习</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div>
                    <span class="light">合作伙伴：</span>
                    <img src="../img/footer_alllogo@2x.png" alt="" class="all-logo">
                </div>
            </div>
        </section>
         <div class="wrap">
                <section class="friend-link">
                    <span class="title">友情链接：</span>
                    <a href="http://www.chanpin100.com/" target="_blank">产品经理</a>
                    <a href="http://www.kejilie.com" target="_blank">科技猎</a>
                    <a href="http://www.huodonghezi.com" target="_blank">活动盒子</a>
                    <a href="http://www.tuicool.com/links" target="_blank">推酷网</a>
                    <a href="http://www.nav80.com/" target="_blank">设计师导航</a>
                    <a href="http://www.pmdaniu.com/" target="_blank">产品大牛</a>
                    <a href="http://www.shxinxuan.cn/" target="_blank">pmp培训</a>
                    <a href="http://xian.xueda.com/" target="_blank">西安家教网</a>
                    <a href="http://www.axure.com.cn" target="_blank">Axure正版</a>
                    <a href="http://www.devstore.cn/" target="_blank">DevStore</a>
                    <a href="http://www.meihaoxueyuan.com" target="_blank">美好学院</a>
                    <a href="http://www.laiyinedu.com/" target="_blank">莱茵教育</a>
                    <a href="http://www.kaikeba.com/link" target="_blank">更多友情链接</a>
                </section>
            </div>

        <section class="copyright">
            <div class="c">
                <p class="links">
                    <a href="http://www.kaikeba.com/about" target="_blank">关于我们</a>
                    <a href="http://www.kaikeba.com/about#contact" target="_blank">联系我们</a>
                    <a href="http://www.kaikeba.com/about#feedback" target="_blank">意见反馈</a>
                </p>
            </div>
            <p>北京开课吧科技有限公司版权所有 京ICP证140465号 京ICP备13032407号-1 京公网安备 11010802013162</p>
        </section>
    </footer>
</div>